import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { ScreenContainer } from '../../components/ScreenContainer';
import { Theme } from '../../constants/Theme';

export default function TermsScreen() {
  return (
    <ScreenContainer>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
        <View style={styles.card}>
          <Text style={styles.title}>Terms of Service</Text>
          <Text style={styles.date}>Effective Date: September 2026</Text>

          <Text style={styles.paragraph}>
            By downloading, browsing, or unlocking prompts through PromptCraft, you agree to abide by these Terms of Service.
          </Text>

          <Text style={styles.sectionTitle}>1. Prompt Library & Intellectual Property</Text>
          <Text style={styles.paragraph}>
            Prompts provided in PromptCraft are curated for personal and commercial usage in AI models (including ChatGPT, Gemini, Claude, Midjourney). You are free to generate content using unlocked prompts for your projects.
          </Text>

          <Text style={styles.sectionTitle}>2. Rewarded Ad System</Text>
          <Text style={styles.paragraph}>
            Unlocking prompt text requires completing a full Google AdMob rewarded advertisement. PromptCraft reserves the right to prevent unlock bypasses or automated script tampering.
          </Text>

          <Text style={styles.sectionTitle}>3. AI Model Outputs</Text>
          <Text style={styles.paragraph}>
            Outputs generated by third-party AI models (OpenAI ChatGPT, Google Gemini) are governed by the respective providers' terms and content policies.
          </Text>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  scroll: {
    padding: Theme.spacing.md,
    paddingBottom: Theme.spacing.xxl,
  },
  card: {
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.borderRadius.xl,
    padding: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: Theme.colors.text,
    marginBottom: 4,
  },
  date: {
    fontSize: 11,
    color: Theme.colors.textMuted,
    marginBottom: Theme.spacing.md,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Theme.colors.primaryLight,
    marginTop: Theme.spacing.md,
    marginBottom: 4,
  },
  paragraph: {
    fontSize: 13,
    color: Theme.colors.textSecondary,
    lineHeight: 19,
  },
});
